{{ include "gitshelves.validateTag" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "gitshelves.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "gitshelves.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "gitshelves.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: gitshelves
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{name: http, containerPort: 8080, protocol: TCP}]
          readinessProbe: {httpGet: {path: /healthz, port: http}}
          livenessProbe: {httpGet: {path: /livez, port: http}}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: ["ALL"]}
          resources: {{- toYaml .Values.resources | nindent 12 }}
