{{- if .Values.ingress.enabled }}
{{- required "ingress.host is required when ingress is enabled" .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gitshelves.fullname" . }}
  labels: {{- include "gitshelves.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- with .Values.ingress.className }}ingressClassName: {{ . }}{{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http: {paths: [{path: /, pathType: Prefix, backend: {service: {name: {{ include "gitshelves.fullname" . }}, port: {name: http}}}}]}
{{- end }}
