from typing import Iterable


def blocks_for_contributions(count: int) -> int:
    """Return the number of stacked blocks for a contribution count.

    Uses a logarithmic scale where 1 block represents 1-9 contributions,
    2 blocks represent 10-99 contributions, and so on. Zero or negative
    counts yield zero blocks.
    """
    if count <= 0:
        return 0
    import math

    return int(math.log10(count)) + 1


def generate_scad(contributions: Iterable[int]) -> str:
    """Generate an OpenSCAD script for a sequence of daily contributions."""
    scad_lines = ["// Generated by gitshelves"]
    block_size = 10  # mm per block cube
    spacing = 12
    for idx, count in enumerate(contributions):
        blocks = blocks_for_contributions(count)
        for level in range(blocks):
            x = idx * spacing
            y = 0
            z = level * block_size
            scad_lines.append(f"translate([{x}, {y}, {z}]) cube({block_size});")
    return "\n".join(scad_lines)
