// Generated by gitshelves
use <<GRIDFINITY_BIN>>;

module contribution_cube() {
    bin(
        ux = 1, uy = 1, uh = 1,
        walls = 1.2, floor = 1.6, lid = "none",
        magnet_pockets = false, stackable = true);
}

unit_height = 7;

module contribution_stack(levels) {
    for (level = [0:levels-1]) {
        translate([0, 0, level * unit_height]) contribution_cube();
    }
}

contribution_stack(3); // 3 cubes
