// Generated by gitshelves
use <<GRIDFINITY_BASEPLATE>>;
use <<GRIDFINITY_BIN>>;

grid_pitch = 42;
baseplate_height = 6;
cube_unit = 7;

module gridfinity_baseplate(grid_x = 1,
                            grid_y = 1,
                            u_height = 6,
                            lip = true,
                            magnet_style = "gridfinity_refine",
                            magnets_corners_only = false,
                            screw_holes = false) {
    include_magnets = !magnets_corners_only;
    gridfinityBaseplate([grid_x, grid_y],
                        grid_pitch,
                        [0, 0],
                        0,
                        bundle_hole_options(
                            refined_hole = magnet_style == "gridfinity_refine",
                            magnet_hole = include_magnets,
                            screw_hole = screw_holes,
                            crush_ribs = true,
                            chamfer = true,
                            supportless = false
                        ),
                        0,
                        [0, 0]);
}

module contribution_stack(levels) {
    for (level = [0:levels-1]) {
        translate([0, 0, baseplate_height + level * cube_unit])
            bin(ux = 1, uy = 1, uh = 1,
                walls = 1.2, floor = 1.6, lid = "none",
                magnet_pockets = false, stackable = true);
    }
}

grid_x = 4;
grid_y = 3;

union() {
    gridfinity_baseplate(grid_x = grid_x,
                         grid_y = grid_y,
                         u_height = baseplate_height,
                         lip = true,
                         magnet_style = "gridfinity_refine",
                         magnets_corners_only = false,
                         screw_holes = false);
    translate([0, 0, 0]) contribution_stack(2); // 2024-01 (12 contributions)
    // 2024-02 (0 contributions) reserved at [42, 0]
    translate([84, 0, 0]) contribution_stack(2); // 2024-03 (98 contributions)
    translate([126, 0, 0]) contribution_stack(3); // 2024-04 (125 contributions)
    translate([0, 42, 0]) contribution_stack(1); // 2024-05 (7 contributions)
    // 2024-06 (0 contributions) reserved at [42, 42]
    translate([84, 42, 0]) contribution_stack(3); // 2024-07 (234 contributions)
    // 2024-08 (0 contributions) reserved at [126, 42]
    translate([0, 84, 0]) contribution_stack(1); // 2024-09 (5 contributions)
    // 2024-10 (0 contributions) reserved at [42, 84]
    // 2024-11 (0 contributions) reserved at [84, 84]
    translate([126, 84, 0]) contribution_stack(2); // 2024-12 (67 contributions)
}
