name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup uv
        uses: astral-sh/setup-uv@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          uv pip install --system pytest pytest-cov coverage
          uv pip install --system -e .
          pytest --cov=gitshelves --cov-report=xml --cov-report=term -q --cov-fail-under=100
          coverage report --fail-under=100
      - name: Upload coverage
        if: hashFiles('coverage.xml') != ''
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: python
          fail_ci_if_error: true
