name: build-stl

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    container:
      image: openscad/openscad:latest
    strategy:
      matrix:
        year: [2021, 2022, 2023, 2024, 2025]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare library folder
      run: mkdir -p openscad/lib
    - name: Fetch Gridfinity library
      run: |
        rm -rf openscad/lib/gridfinity-rebuilt
        git clone --depth 1 https://github.com/kennetek/gridfinity-rebuilt-openscad openscad/lib/gridfinity-rebuilt
    - name: Install Xvfb
      run: |
        apt-get update -qq
        apt-get install -y --no-install-recommends xvfb
    - name: Build STL
      run: |
        mkdir -p stl/${{ matrix.year }}
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
          openscad -o stl/${{ matrix.year }}/baseplate_2x6.stl \
            openscad/baseplate_2x6.scad --export-format binstl
    - name: Upload STL
      uses: actions/upload-artifact@v4
      with:
        name: stl-${{ matrix.year }}
        path: stl/${{ matrix.year }}/baseplate_2x6.stl
