name: build-stl

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: [2021, 2022, 2023, 2024, 2025]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare library folder
      run: mkdir -p openscad/lib
    - name: Fetch Gridfinity library
      run: |
        rm -rf openscad/lib/gridfinity-rebuilt
        git clone --depth 1 https://github.com/kennetek/gridfinity-rebuilt-openscad openscad/lib/gridfinity-rebuilt
    - name: Install OpenSCAD
      run: sudo apt-get update && sudo apt-get install -y openscad
    - name: Build STL
      run: |
        mkdir -p stl/${{ matrix.year }}
        openscad -o stl/${{ matrix.year }}/baseplate_1x12.stl \
          openscad/baseplate_1x12.scad --export-format binstl
    - name: Upload STL
      uses: actions/upload-artifact@v4
      with:
        name: stl-${{ matrix.year }}
        path: stl/${{ matrix.year }}/baseplate_1x12.stl
